'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import useAuth from '@/hooks/useAuth';
import { AuthForm, defaultLoginData } from '@/app/components/auth';

/**
 * Login Page
 * 
 * Configuration-driven login page that uses the AuthForm component.
 * All UI text, labels, and fields come from login.datasource.ts
 * 
 * To customize the login form:
 * 1. Edit login.datasource.ts to change text, fields, labels
 * 2. Edit auth.configuration.json to change styling, behavior
 * 3. Do NOT edit this file unless changing business logic
 */
export default function LoginPage() {
  const router = useRouter();
  const { login } = useAuth();
  
  const [formData, setFormData] = useState<Record<string, string>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [isLoading, setIsLoading] = useState(false);

  /**
   * Handle form field changes
   */
  const handleFieldChange = (fieldName: string, value: string) => {
    setFormData(prev => ({
      ...prev,
      [fieldName]: value
    }));
    
    // Clear error for this field
    if (errors[fieldName]) {
      setErrors(prev => {
        const newErrors = { ...prev };
        delete newErrors[fieldName];
        return newErrors;
      });
    }
  };

  /**
   * Validate form data
   */
  const validateForm = (data: Record<string, string>): boolean => {
    const newErrors: Record<string, string> = {};

    if (!data.usernameOrEmail?.trim()) {
      newErrors.usernameOrEmail = 'Username or email is required';
    }

    if (!data.password) {
      newErrors.password = 'Password is required';
    } else if (data.password.length < 6) {
      newErrors.password = 'Password must be at least 6 characters';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  /**
   * Handle action dispatches from the AuthForm
   * Maps actionId to business logic
   */
  const handleAction = async (actionId: string, data?: Record<string, unknown>) => {
    switch (actionId) {
      case 'auth.login.submit':
        await handleLoginSubmit(data as Record<string, string>);
        break;
      
      case 'auth.navigate.register':
        router.push('/register');
        break;
      
      default:
        console.warn(`Unhandled action: ${actionId}`);
    }
  };

  /**
   * Handle login submission
   */
  const handleLoginSubmit = async (data: Record<string, string>) => {
    if (!validateForm(data)) {
      return;
    }

    setIsLoading(true);
    setErrors({});

    try {
      await login(data.usernameOrEmail, data.password);
      router.push('/dashboard');
    } catch (error) {
      setErrors({
        general: error instanceof Error ? error.message : 'Login failed. Please check your credentials.'
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <AuthForm
      {...defaultLoginData}
      onAction={handleAction}
      onFieldChange={handleFieldChange}
      formData={formData}
      errors={errors}
      loading={isLoading}
    />
  );
}
