'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import useAuth from '@/hooks/useAuth';
import { AuthForm, defaultRegisterData, passwordRequirements } from '@/app/components/auth';

/**
 * Register Page
 * 
 * Configuration-driven registration page that uses the AuthForm component.
 * All UI text, labels, and fields come from register.datasource.ts
 * 
 * To customize the registration form:
 * 1. Edit register.datasource.ts to change text, fields, labels
 * 2. Edit auth.configuration.json to change styling, behavior
 * 3. Do NOT edit this file unless changing business logic
 */
export default function RegisterPage() {
  const router = useRouter();
  const { register } = useAuth();
  
  const [formData, setFormData] = useState<Record<string, string>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [isLoading, setIsLoading] = useState(false);

  /**
   * Handle form field changes
   */
  const handleFieldChange = (fieldName: string, value: string) => {
    setFormData(prev => ({
      ...prev,
      [fieldName]: value
    }));
    
    // Clear error for this field
    if (errors[fieldName]) {
      setErrors(prev => {
        const newErrors = { ...prev };
        delete newErrors[fieldName];
        return newErrors;
      });
    }
  };

  /**
   * Validate form data
   */
  const validateForm = (data: Record<string, string>): boolean => {
    const newErrors: Record<string, string> = {};

    // Username validation
    if (!data.username?.trim()) {
      newErrors.username = 'Username is required';
    } else if (data.username.length < 3) {
      newErrors.username = 'Username must be at least 3 characters';
    } else if (!/^[a-zA-Z0-9_]+$/.test(data.username)) {
      newErrors.username = 'Username can only contain letters, numbers, and underscores';
    }

    // Email validation
    if (!data.email?.trim()) {
      newErrors.email = 'Email is required';
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)) {
      newErrors.email = 'Please enter a valid email address';
    }

    // Password validation using configured requirements
    if (!data.password) {
      newErrors.password = 'Password is required';
    } else {
      const failedRequirements = passwordRequirements.filter(req => !req.validator(data.password));
      if (failedRequirements.length > 0) {
        newErrors.password = 'Password must meet all requirements';
      }
    }

    // Confirm password validation
    if (!data.confirmPassword) {
      newErrors.confirmPassword = 'Please confirm your password';
    } else if (data.password !== data.confirmPassword) {
      newErrors.confirmPassword = 'Passwords do not match';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  /**
   * Handle action dispatches from the AuthForm
   * Maps actionId to business logic
   */
  const handleAction = async (actionId: string, data?: Record<string, unknown>) => {
    switch (actionId) {
      case 'auth.register.submit':
        await handleRegisterSubmit(data as Record<string, string>);
        break;
      
      case 'auth.navigate.login':
        router.push('/login');
        break;
      
      default:
        console.warn(`Unhandled action: ${actionId}`);
    }
  };

  /**
   * Handle registration submission
   */
  const handleRegisterSubmit = async (data: Record<string, string>) => {
    if (!validateForm(data)) {
      return;
    }

    setIsLoading(true);
    setErrors({});

    try {
      await register(data.username, data.email, data.password);
      router.push('/dashboard');
    } catch (error) {
      setErrors({
        general: error instanceof Error ? error.message : 'Registration failed. Please try again.'
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <AuthForm
      {...defaultRegisterData}
      onAction={handleAction}
      onFieldChange={handleFieldChange}
      formData={formData}
      errors={errors}
      loading={isLoading}
    />
  );
}
